### PR TITLE
PRC: readability: replaced secret operator

### PR DESCRIPTION
**Pull request by briankelly13**
I replaced the Perl secret Saturn operator with more readable, but still compact, code.

### CODE REVIEW

**Comment by mohawk2** [comment]
Won't this also be less efficient?

**Comment by Grinnz** [comment]
Yes. I see no reason to change it but here is a closer suggestion:

```
my $d = my @m = $s =~ /(\.)/g;
```

**Comment by briankelly13** [comment]
In some quick testing, the proposed code is actually performing better for
me, in the neighborhood of half the time. I would also guess it's using
less memory because it's not allocating a temporary array.

**Comment by briankelly13** [comment]
Not a big deal. If this isn't really being maintained, no worries. I'm just teaching myself this flow and this looked like something I could improve quickly. Thanks for your feedback.

**Comment by Leont** [comment]
Wouldn't that just be
~~~~
my $d = $s =~ tr/.//
~~~~

**Comment by shadowcat-mst** [comment]
replacing =()= with something uglier and less idiomatic doesn't seem like a gain to me. leont's proposed alternative would be ok.

**Comment by karenetheridge** [comment]
I agree that `=()=` is ideomatic -- it even has an entry in `perlsecret.pod` so it isn't *that* obscure.

However, it would certainly be reasonable to add a comment explaining what it's doing - e.g. `# force list context, to get a match count`.

**Comment by briankelly13** [comment]
Commenting it was the first thing I thought of, but once I figured out that this plumbing/template-ish type code, I just figured readability was more important. The performance gain was a happy side effect.

Not a big thing. Feel free to reject the PR.

**Pull request closed without merging**
